# Generated by Django 5.1.1 on 2024-10-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry_supervisor', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_feedbacks', to='student.student'),
        ),
        migrations.AddField(
            model_name='industrysupervisor',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry_supervisor.industrysupervisor'),
        ),
    ]
