# Generated by Django 5.1.1 on 2024-10-20 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry_supervisor', '0001_initial'),
        ('school_supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('industry_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry_supervisor.industrysupervisor')),
                ('school_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_supervisor.schoolsupervisor')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
